# R for travis: https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
warnings_are_errors: false

r:
  - bioc-release
  - oldrel
  - release
  - devel

r_packages:
  - covr
  - devtools
  - tidyverse
  - shiny

after_success:
  - Rscript -e 'library(covr); codecov()'
